tutorial from https://transport-systems.imperial.ac.uk/tf/60008_21/n2_5_hungarian_algorithm.html#:~:text=The%20algorithm%20has%20two%20stages,has%20the%20cost_matrix%20as%20input.

In [4]:
import numpy as np
import copy

max_int = 100
n = 5
# cost_matrix = np.random.randint(max_int, size=(n,n))
cost_matrix = [[24, 60, 61,  2,  4],
 [38, 89, 30, 51, 93],
 [ 6, 48, 32, 70, 48],
 [39, 30,  0, 59,  1],
 [3, 43, 89, 56, 50]]

cost_matrix = np.array(cost_matrix)

print(cost_matrix)

[[24 60 61  2  4]
 [38 89 30 51 93]
 [ 6 48 32 70 48]
 [39 30  0 59  1]
 [ 3 43 89 56 50]]


In [5]:
# import scipy's linear_sum_assignment
from scipy.optimize import linear_sum_assignment

# execute the assignment
scp_assignment = linear_sum_assignment(cost_matrix)

print('scp_assignment: ', scp_assignment)
# find the total cost
scp_total = 0
for i in range(len(scp_assignment[0])):
    scp_total += cost_matrix[scp_assignment[0][i], scp_assignment[1][i]]
print('scp_totat cost: ', scp_total)

scp_assignment:  (array([0, 1, 2, 3, 4], dtype=int64), array([3, 2, 0, 4, 1], dtype=int64))
scp_totat:  82


# Part 2 - Full implementation of the Hungarian Algorithm
This section presents a step-by-step implementation of the algorithm.

The algorithm has two stages, first we find the minimum value at each row, and then subtract that value to every element of the row. Then we repeat the process using the columns instead. We define this process in the function hungarian_step that has the cost_matrix as input.

In [7]:
def hungarian_step(mat): 
    #The for-loop iterates through every column in the matrix so we subtract this value to every element of the row
    for row_num in range(mat.shape[0]): 
        pass
    #We repeat the process for the columns
    for col_num in range(mat.shape[1]): 
        pass
    
    return mat

In [8]:
hung_matrix = hungarian_step(cost_matrix.copy())
print(hung_matrix)

[[22 58 59  0  2]
 [ 8 59  0 21 63]
 [ 0 42 26 64 42]
 [39 30  0 59  1]
 [ 0 40 86 53 47]]
[[22 28 59  0  1]
 [ 8 29  0 21 62]
 [ 0 12 26 64 41]
 [39  0  0 59  0]
 [ 0 10 86 53 46]]


The next step, while easy to carry out visually, becomes more difficult to code. We need to find the row containing the least number of zeros first.

The first step to do this is to define a function that finds the minimum number of rows to mark (mark means ye3alem 3ala) that contain a zero value, let's call this min_zeros. Let's assume that the matrix being input is boolean with True where 0 existed and False where non-zero.

Now, mark the column and row as False and repeat, saving the information where the last zero value was retrieved.

By repeating this process, we collect all zeros in the matrix.

![image info](Untitled.png)

In [9]:
def min_zeros(zero_mat, mark_zero, verbose=False):
    if verbose:
        print('finding the min_zeros rows')
    # get the min_row = [number of zeros, row index number]
    pass

    # Marked the specific row and column as False
    pass
    if verbose:
        print('zero_mat: \n', zero_mat)
        print('marked_zero: \n', mark_zero)
        

The expected output of the following code:
```
zero_bool_mat_copy: 
 [[False False False  True False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 []
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True False False  True]
 [False False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
 ```

In [10]:
cur_mat = hung_matrix
zero_bool_mat = (cur_mat == 0)
zero_bool_mat_copy = zero_bool_mat.copy()

marked_zero = []
print('zero_bool_mat_copy: \n', zero_bool_mat_copy)
print('marked_zero: \n', marked_zero)
while (True in zero_bool_mat_copy):
    print('*'*10)
    min_zeros(zero_bool_mat_copy, marked_zero, verbose=True)
    # print('zero_bool_mat_copy: \n', zero_bool_mat_copy)
    # print('marked_zero: \n', marked_zero)
        

zero_bool_mat_copy: 
 [[False False False  True False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 []
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True False False  True]
 [False False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0)]
**********
zero_bool_mat_copy: 
 [[False False False False False]
 [False False False False False]
 [

Now that we extracted the zeros in the matrix, we can mark the rows and columns to determine whether the hungarian algorithm is complete.



In [20]:
def mark_matrix(mat, verbose=False):


    if verbose:
        print('marking the matrix')

    # Transform the matrix to boolean matrix (0 = True, others = False)
    cur_mat = mat
    zero_bool_mat = (cur_mat == 0)
    zero_bool_mat_copy = zero_bool_mat.copy()  # Create a copy for iterative modifications

    if verbose:
        print('the bool matrix: \n', zero_bool_mat_copy)

    # Recording possible answer positions by marked_zero
    marked_zero = []

    # Iteratively mark zeros until no zeros remain in the copy of the boolean matrix
    while (True in zero_bool_mat_copy):
        min_zeros(zero_bool_mat_copy, marked_zero, verbose=verbose)  # Assume 'min_zeros' finds rows/columns with minimum zeros

    # Recording the row and column indexes separately.
    marked_zero_row = []
    marked_zero_col = []
    for i in range(len(marked_zero)):
        marked_zero_row.append(marked_zero[i][0])  # Extract row indexes from marked_zero
        marked_zero_col.append(marked_zero[i][1])  # Extract column indexes from marked_zero
    if verbose:
        print('marked_zero_row: ', marked_zero_row)
        print('marked_zero_col: ', marked_zero_col)

    # Collect rows not containing zeros
    non_marked_row = list(set(range(cur_mat.shape[0])) - set(marked_zero_row))
    if verbose:
        print('non_marked_row: ', non_marked_row)

    # Mark columns with zeros
    marked_cols = []
    check_switch = True
    while check_switch:
        check_switch = False
        # get tha column of the zero whose row isn't in the marked row, then add it to the marked columns
        for i in range(len(non_marked_row)):
            pass
        # Update non_marked_row based on newly marked columns
        for row_num, col_num in marked_zero:
            if row_num not in non_marked_row and col_num in marked_cols:

                non_marked_row.append(row_num)
                check_switch = True

    # Mark rows with zeros
    marked_rows = list(set(range(mat.shape[0])) - set(non_marked_row))  # Find rows containing zeros

    return (marked_zero, marked_rows, marked_cols)


In [19]:
marked_zero, marked_rows, marked_cols = mark_matrix(hung_matrix.copy(), verbose=True)
print(marked_zero, marked_rows, marked_cols)

marking the matrix
the bool matrix: 
 [[False False False  True False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True False False  True]
 [False False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
finding the min_zeros rows
zero_mat: 

In the case where marked rows and columns do not add up to  𝑛
 , we need to adjust the matrix to continue the search.

In [21]:
def adjust_matrix(mat, cover_rows, cover_cols, verbose=False):
    if verbose:
        print("adjusting the matrix")
    cur_mat = mat
    non_zero_element = []
    
    # find the minimum value of an element not in a marked column/row 
    pass

    # substract to all values not in a marked row/column
    pass
    # add to all values in marked rows/column
    pass
    
    if verbose:
        print('adjusted matrix = ', cur_mat)
    return cur_mat

In [22]:
adjust_matrix(hung_matrix.copy(), marked_rows, marked_cols )

array([[32, 28, 59,  0,  1],
       [18, 29,  0, 21, 62],
       [ 0,  2, 16, 54, 31],
       [49,  0,  0, 59,  0],
       [ 0,  0, 76, 43, 36]])

In [15]:
def hungarian_algorithm(cost_matrix, verbose=False):
    
    n = cost_matrix.shape[0]
    cur_mat = copy.deepcopy(cost_matrix)
    
    cur_mat = hungarian_step(cur_mat)
    
    count_zero_lines = 0
        
    while count_zero_lines < n:
        if verbose:
            print('*'*10)
        ans_pos, marked_rows, marked_cols = mark_matrix(cur_mat, verbose=verbose)
        count_zero_lines = len(marked_rows) + len(marked_cols)
        if verbose:
            print('count_zero_lines: ', count_zero_lines)

        if count_zero_lines < n:
            cur_mat = adjust_matrix(cur_mat, marked_rows, marked_cols)
    
    return ans_pos

In [16]:
assignment = hungarian_algorithm(cost_matrix, verbose=True)
print(f"The final assignment is: {assignment}")
print(cost_matrix)

[[22 58 59  0  2]
 [ 8 59  0 21 63]
 [ 0 42 26 64 42]
 [39 30  0 59  1]
 [ 0 40 86 53 47]]
**********
marking the matrix
the bool matrix: 
 [[False False False  True False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False  True False False]
 [ True False False False False]
 [False  True  True False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False False False False]
 [ True False False False False]
 [False  True False False  True]
 [ True False False False False]]
marked_zero: 
 [(0, 3), (1, 2), (2, 0), (3, 1)]
finding the min_zeros rows
zero_mat: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True False False  True]
 [False False Fal

In [17]:
total = 0
for i in range(len(assignment)):
    total += cost_matrix[assignment[i][0], assignment[i][1]]
print(f"The total cost of the assignment is {total}")

The total cost of the assignment is 82
